# Generated by Django 5.1.4 on 2026-08-27 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('jaime', '👍'), ('jadore', '❤️'), ('rire', '😂'), ('wow', '😮'), ('triste', '😢')], max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blog.commentaire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('commentaire', 'utilisateur', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='SignalementCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='blog.commentaire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('commentaire', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur_suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_par', to=settings.AUTH_USER_MODEL)),
                ('suiveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi',
                'verbose_name_plural': 'Suivis',
                'unique_together': {('suiveur', 'auteur_suivi')},
            },
        ),
    ]
